<?php

namespace Louvre\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Louvre\BackendBundle\Entity\Command;

/**
 * Command_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends EntityRepository
{
    public function countTickets($date)
    {

        $queryBuilder = $this->createQueryBuilder('c');

        $ticketsSold = $queryBuilder
            ->select('count(ticket.id)')
            ->where('c.visitDate = :visitDate')
            ->setParameter('visitDate', $date)
            ->innerJoin('c.tickets', 'ticket')
            ;

        return $ticketsSold
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
