<?php

namespace Louvre\BackendBundle\Repository;

/**
 * Command_orderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Command_orderRepository extends \Doctrine\ORM\EntityRepository
{
}
