<?php

namespace Louvre\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * Command_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends EntityRepository
{
}
