<?php

namespace Louvre\BackendBundle\Repository;

/**
 * Tickets_commandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tickets_commandRepository extends \Doctrine\ORM\EntityRepository
{
}
