<?php

namespace Louvre\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TicketsRepository extends EntityRepository
{
}
