root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: index
        permanent: true

louvre_backend:
    resource: "@LouvreBackendBundle/Controller/BackendController.php"
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: '%locales%'
    defaults:
        _locale: '%locale%'
