louvre_backend_homepage:
    path:     /homepage
    defaults: { _controller: LouvreBackendBundle:Backend:index }

louvre_backend_commande:
    path:    /commande
    defaults: { _controller: LouvreBackendBundle:Backend:order }

louvre_backend_billets:
    path:    /commande/billets
    defaults: { _controller: LouvreBackendBundle:Backend:billets }
    requirements:

louvre_backend_confirmation:
    path:    /commande/confirmation
    defaults: { _controller: LouvreBackendBundle:Backend:confirmation }

louvre_backend_email:
    path:    /commande/PaiementValide
    defaults: { _controller: LouvreBackendBundle:Backend:email }

louvre_backend_contact:
    path: /contact
    defaults: { _controller: LouvreBackendBundle:Backend:contact }

louvre_backend_cgv:
    path: /cgv
    defaults: { _controller: LouvreBackendBundle:Backend:cgv}
