louvre_backend_homepage:
    path:     /homepage
    defaults: { _controller: LouvreBackendBundle:Backend:index }

louvre_backend_commande:
    path:    /commande
    defaults: { _controller: LouvreBackendBundle:Backend:commande }

louvre_backend_billets:
    path:    /commande/billets
    defaults: { _controller: LouvreBackendBundle:Backend:billets }
    requirements:

louvre_backend_confirmation:
    path:    /commande/confirmation
    defaults: { _controller: LouvreBackendBundle:Backend:confirmation }

louvre_backend_paiement:
    path:    /commande/paiement
    defaults: { _controller: LouvreBackendBundle:Backend:paiement }

louvre_backend_contact:
    path: /contact
    defaults: { _controller: LouvreBackendBundle:Backend:contact }

