services:
#    louvre_backend.example:
#        class: Louvre\BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    louvre_backend.pricecalculator:
        class: Louvre\BackendBundle\PriceCalculator\LouvrePricecalculator

    louvre_backend.louvrevalidator:
        class: Louvre\BackendBundle\DateValidator\LouvreValidator
        arguments:
            - '@session'

    louvre_backend.ticketvalidator:
        class: Louvre\BackendBundle\Validator\TicketValidator
        tags:
            - { name: validator.constraint_validator }
        arguments:
            - '@doctrine.orm.entity_manager'