services:
#    louvre_backend.example:
#        class: Louvre\BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    louvre_backend.pricecalculator:
        class: Louvre\BackendBundle\PriceCalculator\LouvrePricecalculator