services:
#    louvre_backend.example:
#        class: Louvre\BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    louvre_backend.pricecalculator:
        class: Louvre\BackendBundle\PriceCalculator\LouvrePricecalculator

    louvre_backend.ticketvalidator:
        class: Louvre\BackendBundle\Validator\TicketValidator
        tags:
            - { name: validator.constraint_validator, alias: validator.backend.ticketvalidator }
        arguments:
            - '@doctrine.orm.entity_manager'

    louvre_backend.hourvalidator:
         class: Louvre\BackendBundle\Validator\HourValidator
         tags:
            - { name: validator.constraint_validator, alias: validator.backend.hourvalidator }
