<?php

namespace Louvre\BackendBundle\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class Hour extends Constraint
{
    public $message = 'musee.apres.quatorze';

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT; // TODO: Change the autogenerated stub
    }



}