<?php

namespace Louvre\BackendBundle\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class Ticket extends Constraint
{
    public $message = 'Plus de place pour ce jour-ci';

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT; // TODO: Change the autogenerated stub
    }

    public function validatedBy()
    {
        return  get_class($this).'Validator';
    }


}

